// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6AMNVO4YtD-4HbXI-lfEGeNkxyzQPgfM',
    appId: '1:978030382232:web:1f47b7b3e53cf28e5f94ed',
    messagingSenderId: '978030382232',
    projectId: 'flutter-auth-demo-10',
    authDomain: 'flutter-auth-demo-10.firebaseapp.com',
    storageBucket: 'flutter-auth-demo-10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-lHkTKm8qYYg2BvwYzBajwaOVPb5GZCg',
    appId: '1:978030382232:android:bdfe80ff8554b0df5f94ed',
    messagingSenderId: '978030382232',
    projectId: 'flutter-auth-demo-10',
    storageBucket: 'flutter-auth-demo-10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD627YVMReA5QoC-byPJSOM_o_U9qdZMSw',
    appId: '1:978030382232:ios:d7680a3535a428235f94ed',
    messagingSenderId: '978030382232',
    projectId: 'flutter-auth-demo-10',
    storageBucket: 'flutter-auth-demo-10.appspot.com',
    iosClientId: '978030382232-u2kj9qmjq9s3g1pas0ojujmfu0k21nnv.apps.googleusercontent.com',
    iosBundleId: 'org.photon.flutterauthdemo.flutterAuthDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD627YVMReA5QoC-byPJSOM_o_U9qdZMSw',
    appId: '1:978030382232:ios:d7680a3535a428235f94ed',
    messagingSenderId: '978030382232',
    projectId: 'flutter-auth-demo-10',
    storageBucket: 'flutter-auth-demo-10.appspot.com',
    iosClientId: '978030382232-u2kj9qmjq9s3g1pas0ojujmfu0k21nnv.apps.googleusercontent.com',
    iosBundleId: 'org.photon.flutterauthdemo.flutterAuthDemo',
  );
}
